export const DEP = {
  PENDING: 'DEP_PENDING',
  SUCCESS: 'DEP_SUCCESS',
  ERROR: 'DEP_ERROR'
};

export const EMPLOYE = {
  PENDING: 'EMPLOYE_PENDING',
  SUCCESS: 'EMPLOYE_SUCCESS',
  ERROR: 'EMPLOYE_ERROR',

  CHANGE_DATA: 'EMPLOYE_CHANGE_DATA'
};